### ISSUE TITLE
Add github enterprise support

### ISSUE THREAD

**Issue by nwest1** [atom/teletype-server#33]
It'd be cool to be able to configure and host your own server internally.

**Comment by jasonrudolph** [comment]
If you're willing to spend some time provisioning and configuring things on your end, you can probably host this on your own internal server right now. The [steps in the README](https://github.com/atom/teletype-server/tree/769bd7c4f8ecea2db596f72378bdf50f783ab538#running-locally) should be a good starting point.

We probably don't have the resources to provide much support for people running their own server, but the Atom package already allows you to [specify a custom server URL](https://github.com/atom/teletype/blob/5de8cb8cd0e71c86b45f8c308cb37578e861310e/package.json#L40-L46). Once you have your server up and running, you can go to the settings view for the Teletype package, update the URL to point to your internal server, reload Atom, and you should be on your way. I hope this helps!

**Comment by nwest1** [comment]
Thank you! And yes, it seems really ready to easily host your own- could
you explain the github clientId/secret and how that’s configured.

**Comment by jasonrudolph** [comment]
> could you explain the github clientId/secret and how that’s configured.

This [help article](https://help.github.com/enterprise/2.11/admin/guides/user-management/using-github-oauth/) describes the process for creating an OAuth app in a GitHub Enterprise instance.

Once you create the app, you'll see its Client ID and Client Secret in the GitHub Enterprise UI. You'll need to [specify those values in your `.env` file](https://github.com/atom/teletype-server/blob/769bd7c4f8ecea2db596f72378bdf50f783ab538/.env.example#L12-L13).

Currently, the app assumes that you want to make request to https://api.github.com:

https://github.com/atom/teletype-server/blob/769bd7c4f8ecea2db596f72378bdf50f783ab538/lib/identity-provider.js#L17

To use your GitHub Enterprise instance, you'll need to change that URL to point to the API on your GitHub Enterprise instance.

If you wanted to make this configurable, we'd welcome a pull request that replaces the hard-coded api.github.com URL with an environment variable (i.e., `GITHUB_API_URL`).

I hope that helps.
