### ISSUE TITLE
Add functionality to negotiate github oauth token generation

### ISSUE THREAD

**Issue by nwest1** [atom/teletype-server#38]
Would it make sense to include the github app oauth functionality to be served from `/` and not just the `https://teletype.atom.io/auth/teletype/token` site?

The atom package could link to the configured teletype-server and negotiate the necessary oauth token generation.

**Comment by jasonrudolph** [comment]
> Would it make sense to include the github app oauth functionality to be served from `/` and not just the `https://teletype.atom.io/auth/teletype/token` site?

Right now, `teletype-server` provides a small RESTful API. It's JSON in and JSON out. :sweat_smile:

https://teletype.atom.io provides the UI optimized for humans (i.e., HTML, images, CSS, JavaScript, and OAuth redirects).

So while it would be technically possible to move the behavior of https://teletype.atom.io/auth/teletype/token into `teletype-server`, that would mean that `teletype-server` is no longer the small RESTful API that it is today.

We prefer to let `teletype-server` remain a small RESTful API. I hope that makes sense.
