### ISSUE TITLE
Teletype for on-prem? 

### ISSUE THREAD

**Issue by sa02** [atom/teletype-server#44]
Is it possible to start a fork of teletype-server without dependency on Pusher or is it tied to all communication?  

Thanks, 
Steve

**Comment by 50Wliu** [comment]
See #35, specifically https://github.com/atom/teletype-server/issues/35#issuecomment-345106140 if you'd like to help out in that regard.

**Comment by sa02** [comment]
Thanks for the guidance! =D @50Wliu
